In [1]:
# Load packages
import pandas as pd 
import time
import re

## Importing Datasets

In [2]:
google_play_store = pd.read_csv(r'C:\Users\User\TSAP-UberEats-1\Jay_WebScraping\Final_Google_Play_Store\Google_Playstore.csv')
google_play_store.head()

,review,date,stars,name,source
0,Edit: they brought the feature back! Used to b...,"January 18, 2024",Rated 5 stars out of five stars,Rufus Wright,Google Play Store
1,Lately it's very common to wait over 2 hours f...,"January 20, 2024",Rated 1 stars out of five stars,Bastian H,Google Play Store
2,Love it. Great offers. Good selections. Food a...,"January 20, 2024",Rated 5 stars out of five stars,Andrew Higgs,Google Play Store
3,Very disappointed in this app. I've used it fo...,"January 19, 2024",Rated 1 stars out of five stars,Kristi B,Google Play Store
4,Fairly easy to use but trying to find out what...,"January 20, 2024",Rated 2 stars out of five stars,broomee c,Google Play Store

In [3]:
consumeraffairs = pd.read_csv(r'C:\Users\User\TSAP-UberEats-1\Jay_WebScraping\consumer-affairs\UberEats_consumeraffairs.csv')
consumeraffairs.head()

,review,name,state,stars,date,source
0,My spouse accidentally placed an order on the ...,Aria,"San Diego, CA",1,"January 22, 2024",Consumer Affairs
1,"Seen a promotion, used the promotion before ch...",Aleta,"Columbus, OH",1,"January 22, 2024",Consumer Affairs
2,"Been on the phone for two hours, been transfer...",Erica,"Farmington, MI",1,"January 20, 2024",Consumer Affairs
3,I ordered with my wrong address. I then change...,le,"Zionsville, IN",1,"January 20, 2024",Consumer Affairs
4,I came upon a promotion on Uber Eats to purcha...,Ijeoma,"Winnipeg, MB",1,"January 19, 2024",Consumer Affairs

In [4]:
productreview = pd.read_csv(r'C:\Users\User\TSAP-UberEats-1\Jay_WebScraping\productreview\ubereats_productreview.csv')
productreview.head()

,review,date,stars,name,source,title
0,PLEASANT UNEXPECTED CUSTOMER SERVICEI gave Ube...,2024-01-17T06:21:07.000Z,5,evelweevil,productreview,PLEASANT UNEXPECTED CUSTOMER SERVICE
1,UberEats or shall be known as UberEats Money i...,2023-12-15T00:15:44.000Z,5,Cruella Devil,productreview,UberEats or shall be known as UberEats Money i...
2,Delivery delaysWe were provided with a final t...,2023-12-09T07:38:46.000Z,5,Car,productreview,Delivery delays
3,Uber eat fast and easyFast and easy\nI would s...,2023-11-26T01:12:39.000Z,5,You,productreview,Uber eat fast and easy
4,Used uber eats for the first timeExcellent com...,2023-10-12T02:28:37.000Z,5,Fabian G.,productreview,Used uber eats for the first time

In [5]:
sitejabber = pd.read_csv(r'C:\Users\User\TSAP-UberEats-1\Jet_WebScraping\review.csv')
sitejabber.head()

,review,date,stars,name,source
0,Consistent bad quality food delivered. 6 month...,"December 10th, 2023",1,Thomas B.,sitejabber
1,Had an issue with the website freezing up/cras...,"January 9th, 2024",1,Travis S.,sitejabber
2,RIPPED OFF and NO Recourse! Absolute Goat-Rope...,"January 28th, 2021",1,John S.,sitejabber
3,"This is not my first issue with Uber Eats, but...","October 16th, 2023",1,Howard C.,sitejabber
4,Company filled with Thieves\nThey Are absolute...,"August 4th, 2020",1,James n.,sitejabber

In [6]:
sitejabber.nunique()

review    1084
date       592
stars        5
name      1042
source       1
dtype: int64

In [7]:
TrustPilot = pd.read_csv(r'C:\Users\User\TSAP-UberEats-1\Azrul_WebScraping\TrustPilot.csv')
TrustPilot.head()

,review,date,stars,name,source
0,So so. Usually everything is delivered on time...,"Date of experience: January 21, 2024",Rated 3 out of 5 stars,DO,Trust Pilot
1,I have ordered a McDonald’s through McDonald’s...,"Date of experience: January 19, 2024",Rated 3 out of 5 stars,Joanne Hensleigh,Trust Pilot
2,I ordered a vegan burger using Uber eats and w...,"Date of experience: January 16, 2024",Rated 5 out of 5 stars,KB,Trust Pilot
3,"They keep sending me emails with a promo, let ...","Date of experience: January 20, 2024",Rated 2 out of 5 stars,Kristi,Trust Pilot
4,I have been billed 2 items that didn't arrive ...,"Date of experience: January 19, 2024",Rated 2 out of 5 stars,EW,Trust Pilot

In [8]:
TrustPilot.nunique()

review    4976
date       223
stars        5
name      1514
source       1
dtype: int64

In [9]:
TrustPilot.shape

(5000, 5)

### Merging Datsets

In [10]:
result = pd.concat([google_play_store, consumeraffairs,productreview,sitejabber,TrustPilot])

In [11]:
result

,review,date,stars,name,source,state,title
0,Edit: they brought the feature back! Used to b...,"January 18, 2024",Rated 5 stars out of five stars,Rufus Wright,Google Play Store,NaN,NaN
1,Lately it's very common to wait over 2 hours f...,"January 20, 2024",Rated 1 stars out of five stars,Bastian H,Google Play Store,NaN,NaN
2,Love it. Great offers. Good selections. Food a...,"January 20, 2024",Rated 5 stars out of five stars,Andrew Higgs,Google Play Store,NaN,NaN
3,Very disappointed in this app. I've used it fo...,"January 19, 2024",Rated 1 stars out of five stars,Kristi B,Google Play Store,NaN,NaN
4,Fairly easy to use but trying to find out what...,"January 20, 2024",Rated 2 stars out of five stars,broomee c,Google Play Store,NaN,NaN
...,...,...,...,...,...,...,...
4995,Delivery driver turns up with the incorrect or...,"Date of experience: July 31, 2023",Rated 1 out of 5 stars,DI,Trust Pilot,NaN,NaN
4996,There was a great deal on Buddies Pizza buy on...,"Date of experience: July 28, 2023",Rated 5 out of 5 stars,PA,Trust Pilot,NaN,NaN
4997,Very prompt service and excellent communication!,"Date of experience: July 29, 2023",Rated 5 out of 5 stars,RW,Trust Pilot,NaN,NaN
4998,Thieves who don’t refund you if your order is ...,"Date of experience: July 20, 2023",Rated 1 out of 5 stars,MI,Trust Pilot,NaN,NaN
4999,Food arrived before the estimate time. Was in...,"Date of experience: July 30, 2023",Rated 5 out of 5 stars,EG,Trust Pilot,NaN,NaN

In [12]:
result.nunique()

review    11621
date       1430
stars        15
name       7909
source        5
state       193
title       331
dtype: int64

In [13]:
result.to_csv('UberEatsReviews.csv', index = False, header=True)